{{ $component := (dict "Global" $ "Component" "website-joana") }}

apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "common.names.full" $component }}
  labels: {{ include "common.labels" $component | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels: {{ include "common.labels" $component | nindent 6 }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 50%
      maxUnavailable: 0
  template:
    metadata:
      annotations:
        {{- range $annotation, $value := .Values.base.annotations}}
        {{ $annotation | quote }}: {{ $value | quote }}
        {{- end }}
      labels: {{ include "common.labels" $component | nindent 8 }}
    spec:
      containers:
        - name: {{ $component.Component }}
          image: {{ include "common.images.image" $ }}
          ports:
            - name: http
              containerPort: 4000
