{{ $component := (dict "Global" $ "Component" "website-joana") }}

{{- if .Values.website.ingress }}
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: {{ include "common.names.full" $component }}
  labels: {{ include "common.labels"  $component | nindent 4 }}
  annotations: {{ .Values.website.ingress.annotations | toYaml | nindent 4 }}
spec:
  rules:
    - host: {{ .Values.website.ingress.host }}
      http:
        paths:
          - path: /
            backend:
              serviceName: {{ include "common.names.full" $component }}
              servicePort: http
    - host: "www.{{ .Values.website.ingress.host }}"
      http:
        paths:
          - path: /
            backend:
              serviceName: {{ include "common.names.full" $component }}
              servicePort: http
  tls:
    - hosts:
        - {{ .Values.website.ingress.host }}
        - www.joanacpereira.me
      secretName: {{ include "common.names.full" $component }}-tls
  {{- end }}
