{{ $component := (dict "Global" $ "Component" "website-joana") }}

apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ include "common.names.full" $component }}
  labels: {{ include "common.labels" $component | nindent 4}}
data:
  {{- range $secret, $value := .Values.website.secrets }}
  {{ $secret }}: {{ $value | quote }}
  {{- end }}
